# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Person.create(name: "Bertrand")
Person.create(name: "Damien")
Person.create(name: "Anthony")
Person.create(name: "Thomas")
Person.create(name: "Marc")
Person.create(name: "Sophie")
Person.create(name: "Guillaume")
Person.create(name: "Jade")
Person.create(name: "Philippe")
Person.create(name: "Anas")
Person.create(name: "Najib")
Person.create(name: "Antoine")
Person.create(name: "Thierry")
Person.create(name: "Vincent")
Person.create(name: "Alexis")
Person.create(name: "Julie")
Person.create(name: "Naima")
Person.create(name: "Francois")
Person.create(name: "Othman")
Person.create(name: "Caroline")
Person.create(name: "Didier")
Person.create(name: "Manoel")
Person.create(name: "Sabrina")
